spring.application.name=Fiszki
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
openai.api.key=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
